### ISSUE TITLE
[Suggestion] Add a "simple" mode

### ISSUE THREAD

**Issue by UnBeatWaterGH** [pwitvoet/wadmaker#5]
A simple mode where SpriteMaker would write Indexed PNGs, it's fine writing config files and renaming files and such (even though I'd rather have it ONLY take a sprite and convert it to PNGs exactly as it was), and don't create color palettes, and remove support for PSD and all those extra formats, we only need PNGs, be basic, do nothing extra. I just wanna edit HUD graphics without the craziness that these tools do.

While yes, it's cool that your tool can do all kinds of crap automatically, I don't need to read PSDs, I can convert those to PNGs with ImageMagick, I don't need auto palette generation, I can do that with ImageMagick.

Your tool simply does too much, when the only reason I need it, is to read and write ONE format.

**Comment by pwitvoet** [comment]
If you think it's doing too much 'crap', then perhaps SpriteMaker isn't the right tool for you.

The purpose of SpriteMaker is to make Half-Life/GoldSource sprites with as little hassle as possible. That's why it can directly convert Photoshop and Krita files and 32-bit images with alpha channels, and why I plan to add support for more formats in the future. Converting sprites back to images is a secondary feature, and although I do plan to add some more format-related options for that, the default output format will continue to be a 32-bit png.

**Comment by UnBeatWaterGH** [comment]
> then perhaps SpriteMaker isn't the right tool for you.

I have not as of yet been able to find another tool (though goldutil *might* be what I need, but I haven't tried it yet), SpriteMaker is all I've been able to find.

**Comment by pwitvoet** [comment]
So what exactly is the issue then? If you just want to modify an existing sprite, it won't get much simpler than this:
- `SpriteMaker.exe yourhud.spr` --> `yourhud.png` (the exact filename depends on the type of sprite)
- Edit `yourhud.png` with an image editor
- `SpriteMaker.exe yourhud.png` --> `yourhud.spr`

As for all the other features, just ignore them if you don't need them, they shouldn't get in your way.

**Comment by UnBeatWaterGH** [comment]
> So what exactly is the issue then? If you just want to modify an existing sprite, it won't get much simpler than this:
> 
>     * `SpriteMaker.exe yourhud.spr` --> `yourhud.png` (the exact filename depends on the type of sprite)
> 
>     * Edit `yourhud.png` with an image editor
> 
>     * `SpriteMaker.exe yourhud.png` --> `yourhud.spr`
> 
> 
> As for all the other features, just ignore them if you don't need them, they shouldn't get in your way.

Alright, but I've found an alternative to your software that is so small (no file ever reached over 1k lines) that I've looked at the entire code, and it has basically no (extra) features and only converts an indexed png to a sprite, and of course the other way around. It also has support for WADs as well. It happens to be [goldutil](https://github.com/L-P/goldutil).

**Comment by pwitvoet** [comment]
So with 'simple mode' you actually meant 'the code should be as simple as possible', not 'making sprites should be as simple as possible'. That's a very different design goal. Oh well, good that there's a tool that does work for you.
